### ISSUE TITLE
"Read more" button showing for products when "add to chart" button is disabled

### ISSUE THREAD

**Issue by rafaelsaback** [Codeinwp/elementor-extra-widgets#15]
I suggest adding the following condition:
```php
$settings['grid_post_type'] !== 'product' &&
```
to the `elseif` statement below:
https://github.com/Codeinwp/elementor-extra-widgets/blob/a1fc5d0bff05594e717c72217b1b3444c7b1bae5/widgets/elementor/posts-grid.php#L1721

The "Read more" should only be visible if the post type is not product.

**Comment by cristian-ungureanu** [comment]
Thanks for reporting this but the "Read more" does not come from that. If the post type is product, the if statement will enter in the first case anyways. The "read more" appears for the products that are out of stock. It's the text that WooCommerce returns with the "add_to_cart_text()" function that we call to get the button's label.
